version: "3"
services:
  grafana:
    image: docker.io/grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - management-network 
    volumes:
      - grafana-data:/var/lib/grafana

  influxdb:
    image: docker.io/influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
      - 8089:8089/udp
    networks:
      - management-network 
    volumes:
      - influxdb-data:/var/lib/influxdb

  organizr:
    image: docker.io/organizr/organizr
    container_name: organizr
    restart: always
    ports:
      - 8000:80
    environment:
      - PGID=1001
      - PUID=1001
      - fpm=true # optional, remove this line if not needed
      - branch=v2-master  # optional, remove this line if not needed
    volumes:
      - organizr-data:/config

  docker_registry_web:
    image: docker.io/hyper/docker-registry-web
    container_name: registry-web
    restart: always
    links:
      - registry-srv
    ports:
      - 8080:8080
    environment:
      - REGISTRY_URL=https://registry-srv:5000/v2
      - REGISTRY_TRUST_ANY_SSL=true
      - REGISTRY_BASIC_AUTH="YWRtaW46Y2hhbmdlbWU="
      - REGISTRY_NAME=localhost:5000 hyper/docker-registry-web
    volumes:
      - registry-web-data:/data

  registry-srv:
    image: docker.io/registry
    container_name: registry-srv
    restart: always
    ports:
      - 5000:5000
    volumes:
      - registry-srv-data:/etc/docker/registry
      - registry-srv-auth:/etc/docker/registry/auth

networks:
  management-network:

volumes:
  grafana-data:
    external: true
  influxdb-data:
    external: true
  organizr-data:
    external: true
  registry-web-data:
    external: true
  registry-srv-data:
    external: true
  registry-srv-auth:
    external: true